# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('dataId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('dataId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=2)),
                ('tariff', models.CharField(max_length=2)),
            ],
        ),
    ]
